#!/bin/sh
# usage: iframe route title url
mkdir -p releases
cd releases
mkdir $1
cd $1
cat <<EOF >> index.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../public/css/iframe.css">
    <title>$2</title>
</head>

<body>
    <iframe src="$3">Click this <a
            href="$3">link</a> if you don't see the iframe.</iframe>
</body>

</html>
EOF