[[links]]
label = "Latest Release"
icon = "latest.png"
target = "/releases/out-world"

[[links]]
label = "Buy Me a Coffee"
icon = "ko-fi.png"
target = "https://ko-fi.com/norizon"
class = "hover-invert"

[[links]]
label = "GitHub"
icon = "github.png"
target = "https://github.com/norinorin"
class = "hover-uninvert"

[[links]]
label = "Spotify"
icon = "spotify.png"
target = "https://open.spotify.com/artist/3HCMHW2drI3phTu5Qh8cAM"
class = "hover-uninvert"

[[links]]
label = "SoundCloud"
icon = "soundcloud.png"
target = "https://soundcloud.com/norizon16"
class = "hover-uninvert"

[[links]]
label = "osu!"
icon = "osu.png"
target = "https://osu.ppy.sh/u/18414534"
class = "hover-uninvert"

[[links]]
label = "Discord"
icon = "discord.png"
target = "https://discord.gg/4KPMCum"
class = "hover-uninvert"
