#!/bin/bash
cd static/public/assets
mkdir -p thumbnails
for file in ./*; do
    if [ -f "$file" ] && [ ! -f "thumbnails/$file" ]; then
        convert $file -resize 128x128 "thumbnails/$file"
    fi
done
